#
# monitor rbac
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor-controller
  namespace: k8s-test

---

apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-monitor-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - deployments
  - services
  verbs:
  - get
  - list
  - watch

---

apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-monitor-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-monitor-controller
subjects:
- kind: ServiceAccount
  name: pod-monitor-controller
  namespace: k8s-test
