go_build:
	go build -o main .

go_build_pro:
	go build -tags=pro -o main_pro .

go_build_enterprise:
	go build -tags=enterprise -o main_enterprise .

go_build_enterprise_pro:
	go build -tags="pro enterprise" -o main_enterprise_pro .

clear:
	rm main main_pro main_enterprise main_enterprise_pro
