// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: constant.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accounting_ReturnCode int32

const (
	Accounting_SUCCESS        Accounting_ReturnCode = 0
	Accounting_DATABASE_ERROR Accounting_ReturnCode = 900100
	Accounting_NOT_FOUND      Accounting_ReturnCode = 900102
)

// Enum value maps for Accounting_ReturnCode.
var (
	Accounting_ReturnCode_name = map[int32]string{
		0:      "SUCCESS",
		900100: "DATABASE_ERROR",
		900102: "NOT_FOUND",
	}
	Accounting_ReturnCode_value = map[string]int32{
		"SUCCESS":        0,
		"DATABASE_ERROR": 900100,
		"NOT_FOUND":      900102,
	}
)

func (x Accounting_ReturnCode) Enum() *Accounting_ReturnCode {
	p := new(Accounting_ReturnCode)
	*p = x
	return p
}

func (x Accounting_ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accounting_ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_constant_proto_enumTypes[0].Descriptor()
}

func (Accounting_ReturnCode) Type() protoreflect.EnumType {
	return &file_constant_proto_enumTypes[0]
}

func (x Accounting_ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accounting_ReturnCode.Descriptor instead.
func (Accounting_ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_constant_proto_rawDescGZIP(), []int{0, 0}
}

type Accounting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Accounting) Reset() {
	*x = Accounting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accounting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accounting) ProtoMessage() {}

func (x *Accounting) ProtoReflect() protoreflect.Message {
	mi := &file_constant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accounting.ProtoReflect.Descriptor instead.
func (*Accounting) Descriptor() ([]byte, []int) {
	return file_constant_proto_rawDescGZIP(), []int{0}
}

var File_constant_proto protoreflect.FileDescriptor

var file_constant_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x0a, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x40, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x0e, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53, 0x45, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x84, 0xf8, 0x36, 0x12, 0x0f, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x86, 0xf8, 0x36, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x62, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constant_proto_rawDescOnce sync.Once
	file_constant_proto_rawDescData = file_constant_proto_rawDesc
)

func file_constant_proto_rawDescGZIP() []byte {
	file_constant_proto_rawDescOnce.Do(func() {
		file_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_constant_proto_rawDescData)
	})
	return file_constant_proto_rawDescData
}

var file_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_constant_proto_goTypes = []interface{}{
	(Accounting_ReturnCode)(0), // 0: account.Accounting.ReturnCode
	(*Accounting)(nil),         // 1: account.Accounting
}
var file_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constant_proto_init() }
func file_constant_proto_init() {
	if File_constant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_constant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accounting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constant_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_proto_goTypes,
		DependencyIndexes: file_constant_proto_depIdxs,
		EnumInfos:         file_constant_proto_enumTypes,
		MessageInfos:      file_constant_proto_msgTypes,
	}.Build()
	File_constant_proto = out.File
	file_constant_proto_rawDesc = nil
	file_constant_proto_goTypes = nil
	file_constant_proto_depIdxs = nil
}
