// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.0
// source: pb/random.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Random struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomString string `protobuf:"bytes,1,opt,name=randomString,proto3" json:"randomString,omitempty"`
	RandomInt    int32  `protobuf:"varint,2,opt,name=randomInt,proto3" json:"randomInt,omitempty"`
}

func (x *Random) Reset() {
	*x = Random{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_random_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Random) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Random) ProtoMessage() {}

func (x *Random) ProtoReflect() protoreflect.Message {
	mi := &file_pb_random_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Random.ProtoReflect.Descriptor instead.
func (*Random) Descriptor() ([]byte, []int) {
	return file_pb_random_proto_rawDescGZIP(), []int{0}
}

func (x *Random) GetRandomString() string {
	if x != nil {
		return x.RandomString
	}
	return ""
}

func (x *Random) GetRandomInt() int32 {
	if x != nil {
		return x.RandomInt
	}
	return 0
}

var File_pb_random_proto protoreflect.FileDescriptor

var file_pb_random_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4a, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x6e,
	0x74, 0x32, 0x38, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x27, 0x0a, 0x0b, 0x44, 0x6f, 0x53, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x1a, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_random_proto_rawDescOnce sync.Once
	file_pb_random_proto_rawDescData = file_pb_random_proto_rawDesc
)

func file_pb_random_proto_rawDescGZIP() []byte {
	file_pb_random_proto_rawDescOnce.Do(func() {
		file_pb_random_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_random_proto_rawDescData)
	})
	return file_pb_random_proto_rawDescData
}

var file_pb_random_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_random_proto_goTypes = []interface{}{
	(*Random)(nil), // 0: pb.Random
}
var file_pb_random_proto_depIdxs = []int32{
	0, // 0: pb.RandomService.DoSomething:input_type -> pb.Random
	0, // 1: pb.RandomService.DoSomething:output_type -> pb.Random
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_random_proto_init() }
func file_pb_random_proto_init() {
	if File_pb_random_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_random_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Random); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_random_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_random_proto_goTypes,
		DependencyIndexes: file_pb_random_proto_depIdxs,
		MessageInfos:      file_pb_random_proto_msgTypes,
	}.Build()
	File_pb_random_proto = out.File
	file_pb_random_proto_rawDesc = nil
	file_pb_random_proto_goTypes = nil
	file_pb_random_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RandomServiceClient is the client API for RandomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RandomServiceClient interface {
	DoSomething(ctx context.Context, in *Random, opts ...grpc.CallOption) (*Random, error)
}

type randomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomServiceClient(cc grpc.ClientConnInterface) RandomServiceClient {
	return &randomServiceClient{cc}
}

func (c *randomServiceClient) DoSomething(ctx context.Context, in *Random, opts ...grpc.CallOption) (*Random, error) {
	out := new(Random)
	err := c.cc.Invoke(ctx, "/pb.RandomService/DoSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomServiceServer is the server API for RandomService service.
type RandomServiceServer interface {
	DoSomething(context.Context, *Random) (*Random, error)
}

// UnimplementedRandomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRandomServiceServer struct {
}

func (*UnimplementedRandomServiceServer) DoSomething(context.Context, *Random) (*Random, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSomething not implemented")
}

func RegisterRandomServiceServer(s *grpc.Server, srv RandomServiceServer) {
	s.RegisterService(&_RandomService_serviceDesc, srv)
}

func _RandomService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Random)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RandomService/DoSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomServiceServer).DoSomething(ctx, req.(*Random))
	}
	return interceptor(ctx, in, info, handler)
}

var _RandomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RandomService",
	HandlerType: (*RandomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _RandomService_DoSomething_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/random.proto",
}
