// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`            // id
	Name  string    `gorm:"column:name;not null" json:"name"`                             // 名称
	Age   int32     `gorm:"column:age;not null" json:"age"`                               // 年龄
	Ctime time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"` // 创建时间
	Mtime time.Time `gorm:"column:mtime;not null;default:CURRENT_TIMESTAMP" json:"mtime"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
