apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-simple-ingress-controller
  namespace: k8s-test

---

apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-simple-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---

apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-simple-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-simple-ingress-controller
subjects:
- kind: ServiceAccount
  name: k8s-simple-ingress-controller
  namespace: k8s-test

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-simple-ingress-controller
  namespace: k8s-test
  labels:
    app: ingress-controller
spec:
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: k8s-simple-ingress-controller
      containers:
      - name: k8s-simple-ingress-controller
        image: zhengjin/k8s-simple-ingress-controller:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
