//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package sdk

import (
	"github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &gORMDB_{}
		},
	})
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &GORMDB{}
		},
		ParamFactory: func() interface{} {
			var _ paramInterface = &Param{}
			return &Param{}
		},
		ConstructFunc: func(i interface{}, p interface{}) (interface{}, error) {
			param := p.(paramInterface)
			impl := i.(*GORMDB)
			return param.New(impl)
		},
	})
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &GORMDB{}
		},
		ParamFactory: func() interface{} {
			var _ paramInterface = &Param{}
			return &Param{}
		},
		ConstructFunc: func(i interface{}, p interface{}) (interface{}, error) {
			param := p.(paramInterface)
			impl := i.(*GORMDB)
			return param.New(impl)
		},
	})
}

type paramInterface interface {
	New(impl *GORMDB) (*GORMDB, error)
}
type gORMDB_ struct {
	AutoMigrate_ func(dst ...interface{}) error
	Model_       func(value interface{}) GORMDBIOCInterface
	Create_      func(value interface{}) GORMDBIOCInterface
	Where_       func(query interface{}, args ...interface{}) GORMDBIOCInterface
	Find_        func(dest interface{}, conds ...interface{}) GORMDBIOCInterface
	Error_       func() error
}

func (g *gORMDB_) AutoMigrate(dst ...interface{}) error {
	return g.AutoMigrate_(dst...)
}

func (g *gORMDB_) Model(value interface{}) GORMDBIOCInterface {
	return g.Model_(value)
}

func (g *gORMDB_) Create(value interface{}) GORMDBIOCInterface {
	return g.Create_(value)
}

func (g *gORMDB_) Where(query interface{}, args ...interface{}) GORMDBIOCInterface {
	return g.Where_(query, args...)
}

func (g *gORMDB_) Find(dest interface{}, conds ...interface{}) GORMDBIOCInterface {
	return g.Find_(dest, conds...)
}

func (g *gORMDB_) Error() error {
	return g.Error_()
}

type GORMDBIOCInterface interface {
	AutoMigrate(dst ...interface{}) error
	Model(value interface{}) GORMDBIOCInterface
	Create(value interface{}) GORMDBIOCInterface
	Where(query interface{}, args ...interface{}) GORMDBIOCInterface
	Find(dest interface{}, conds ...interface{}) GORMDBIOCInterface
	Error() error
}

func GetGORMDB(p *Param) (*GORMDB, error) {
	i, err := normal.GetImpl(util.GetSDIDByStructPtr(new(GORMDB)), p)
	if err != nil {
		return nil, err
	}
	impl := i.(*GORMDB)
	return impl, nil
}

func GetGORMDBIOCInterface(p *Param) (GORMDBIOCInterface, error) {
	i, err := normal.GetImplWithProxy(util.GetSDIDByStructPtr(new(GORMDB)), p)
	if err != nil {
		return nil, err
	}
	impl := i.(GORMDBIOCInterface)
	return impl, nil
}

func GetGORMDBSingleton(p *Param) (*GORMDB, error) {
	i, err := singleton.GetImpl(util.GetSDIDByStructPtr(new(GORMDB)), p)
	if err != nil {
		return nil, err
	}
	impl := i.(*GORMDB)
	return impl, nil
}

func GetGORMDBIOCInterfaceSingleton(p *Param) (GORMDBIOCInterface, error) {
	i, err := singleton.GetImplWithProxy(util.GetSDIDByStructPtr(new(GORMDB)), p)
	if err != nil {
		return nil, err
	}
	impl := i.(GORMDBIOCInterface)
	return impl, nil
}
