apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
  namespace: k8s-test
data:
  sidecarconfig.yaml: |
    initContainers:
    - name: init-busybox
      image: busybox:1.30
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 3; echo \"init process done.\""]
    containers:
    - name: sidecar-busybox
      image: busybox:1.30
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do echo $(date +'%Y-%m-%d_%H:%M:%S') 'busybox is running ...'; sleep 5; done;"]
    # volumes:
    # - name: busybox-conf
    #   configMap:
    #     name: busybox-configmap
