version: "3"

#
# refer:
# https://hub.docker.com/r/bitnami/kafka
#
# kafka broker config:
# https://kafka.apache.org/documentation/#brokerconfigs
#

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "${HOME}/Downloads/data/docker_zookeeper:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-broker
    ports:
      - "9092:9092"
    volumes:
      - "${HOME}/Downloads/data/docker_kafka:/bitnami/kafka"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=60000
    depends_on:
      - zookeeper
