setup-cluster:
	docker-compose up -d

clearup-cluster:
	docker-compose down

start-cluster:
	docker-compose start zookeeper kafka

stop-cluster:
	docker-compose stop

run-debug:
	go run main.go

run-product-msgs-test:
	./run.sh product
