#
# create read pods role for k8s-test namespace.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-reader
  namespace: k8s-test
rules:
- apiGroups:
  - ""
  resources: ["pods"]
  verbs: ["get", "watch", "list"]