#
# Desc: bind role "pods-reader" with user "k8s-test-ns.default".
# Cmd: kubectl create rolebinding client-pods-reader --role=pods-reader --serviceaccount=k8s-test-ns:default -n k8s-test-ns
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-pods-reader
  namespace: k8s-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-reader
subjects:
- kind: ServiceAccount
  namespace: k8s-test
  name: default